import { auth } from "@/auth";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import { FactoriesSessionProvider } from "@/providers/session-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FactoriesSessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="grid min-h-[100vh] grid-rows-siteGrid gap-10">
              <Header />
              <main>{children}</main>
              <footer>
                <div className="container">footer</div>
              </footer>
            </div>
            <Toaster richColors closeButton />
          </ThemeProvider>
        </FactoriesSessionProvider>
      </body>
    </html>
  );
}
